In [ ]:
#step-1: we have import the dataset to the colab note book.
import pandas as pd #pd is an instance of pandas
df=pd.read_csv('data.csv') #predefine parameter of pandas.

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#step-2: grouping the input columns and output columns and convert the tablier to array formet
x=df.iloc[:,0:3]#slicing the input column

In [ ]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
y=df.iloc[:,3:4]#slicing the output column

In [ ]:
y

Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

In [ ]:
x=x.values #tabler formet convert the array formet

In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y=y.values

In [ ]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [ ]:
# step-3: Handing missing data or Nalivalues.
# scenario-1: missing values of numerical column.
#we have calculate the average of the column replace the average or mean value or empty values.
# scenario-2:missing value in numerical colume.
#fill the value we have replace the empty  values with high repeating values.
# scenario-3: haveing missing values  in huge data set.
#remove those empty values from the data set.

import numpy as np
from sklearn.impute import SimpleImputer #simpleimputer is a class from sklearn .
#which is used to new values placed in the missing values.simpleimputer is a sklearn are packages.
#simpleimputer is a class which  was imported from sklearn package.

imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])


In [ ]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:

#step-4: handling the categorical data
#converting the categorical data into numerical data.
#OneHotencoder is a class which was imported from sklearn package.
#OneHotencoder is used to convert text to binarycode(0,1).
#columntransformer is a class which was to import from sklearn package.
#columntransformer is used  to apply changes or transformer(updating the values present in the data is transformer)
#columntransformer is a class which is used to apply the changes of numeric data in the place of categorical data
#Alexa-0,0,1

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=ct.fit_transform(x)




In [ ]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
#Onehotencoder is only form input column
#linearencoder is only for output column

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#step-5: split the data into training and testing data
#train and test split is a class
#which was imported from sklearn.model_selection.
#it was used for spliting the data into training and testing.

from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

array([[0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [ ]:
x_test

array([[1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [ ]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 1])

In [ ]:
y_test

array([1, 1])

In [ ]:
#step-6:feature scaleing
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])

In [ ]:
x_train

array([[0.0, 1.0, 0.0, 1.7489686653694159, 1.8950579744736393],
       [0.0, 1.0, 0.0, -1.1897884853096492, -0.7985302152479116],
       [0.0, 0.0, 1.0, 0.09999937526616287, -0.9842949179873288],
       [1.0, 0.0, 0.0, 0.8673415201656964, 0.8733521094068442],
       [1.0, 0.0, 0.0, -0.16122348257197638, 0.40894035255830086],
       [0.0, 1.0, 0.0, 0.2795900900298834, 0.1096527759225733],
       [0.0, 0.0, 1.0, -0.014285625038023117, -0.14835375565995101],
       [0.0, 0.0, 1.0, -1.630602057911509, -1.3558243234661633]],
      dtype=object)

In [ ]:
#machine learning
#supervisioned learning - when we have data  and  the model tast are  classification are prediction.
#unsupervisioned learning - unlabel  data, model remembers the patterns. we can perform prediction also.
#rainforcement learning - model will learn form falilures. trail and error method.
#supervisioned learnig is two types
#logistic regression -when the model perform  classification tast,
#we have to apply logistic reggration algorithm(eg:-yes or no,0's and 1's ,true or false).
#linear regression -  when the model perform prediction task,
#we have to apply linear reggration algorithm(eg:-  label or model  prediction).
#step-7:  apply algorithm to the training data for model training
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)



LogisticRegression()

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
y_pred

array([0, 1])